'use strict';

/**
 * @ngdoc overview
 * @name mmmApp
 * @description
 * # mmmApp
 *
 * Main module of the application.
 */
angular
  .module('mmmApp', [
    'ngResource',
    'ui.router',
    'ngMessages'
  ])
  .config(function ($stateProvider,$urlRouterProvider,role) {
    $urlRouterProvider.otherwise('/login');
    $stateProvider
      .state('login',{
        url:'/login',
        controller:'LoginCtrl',
        templateUrl:'views/login.html'
      })
      .state('register',{
        url:'/register',
        //resolve:{
        //  leader_id:function(UserService){
        //    return UserService.leader_id()
        //  }
        //},
        controller:'RegisterCtrl',
        templateUrl:'views/register.html'
      })
      .state('register_bank',{
        url:'/register_bank',
        controller:'RegbankCtrl',
        templateUrl:'views/register_bank.html'
      })
      .state('board',{
        url:'/board/:id',
        controller:'BoardCtrl',
        templateUrl:'views/board.html'
      })
      .state('dashboard',{
        url:'/dashboard',
        abstract:true,
        access_level:role.user,
        views:{
          '':{
            templateUrl:'views/dashboard.html',
            controller:'DashboardCtrl'
          },
          'header@dashboard':{
            templateUrl:'views/header.html',
            controller:'ListCtrl'
          },
          'list@dashboard':{
            templateUrl:'views/list.html',
            controller:'ListCtrl'
          },
          'detail@dashboard':{
            templateUrl:'views/dashboard/fund_management.html',
            controller:'FundManagementCtrl'
          }
        }
      })
      .state('dashboard.password_management',{
        url:'/password_management',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            controller:'UserManagementCtrl',
            templateUrl:'views/dashboard/password_management.html'
          }
        }
      })
      .state('dashboard.account_active_management',{
        url:'/account_active_management',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            controller:'UserManagementCtrl',
            templateUrl:'views/dashboard/account_active_management.html'
          }
        }
      })
      .state('dashboard.summary_management',{
        url:'/summary',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/summary_management.html',
            controller:'SummaryCtrl',
            resolve:{
              summary:function(UserService){
                return UserService.summary();
              }
            }
          }
        }
      })
      .state('dashboard.profile_management',{
        url:'/profile',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/profile_management.html',
            controller:'UserManagementCtrl'
          }
        }
      })
      .state('dashboard.payment_management',{
        url:'/payment',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/payment_management.html',
            controller:'UserManagementCtrl'
          }
        }
      })
      .state('dashboard.fund_management',{
        url:'/fund_management',
        access_level:role.user,
        resolve: {
          FundFlowTo:function(FundFlow){
            return FundFlow.to();
          },
          FundFlowFrom:function(FundFlow){
            return FundFlow.from();
          },
          SystemInfo:function(UserData){
            return UserData.system_info();
          },
          PersonInfo:function(UserData,auth){
            return UserData.query(auth.id);
          }
        },
        onEnter:function(expire){
          expire.clearAll();
          expire.cycleAll();
        },
        onExit:function(expire){
          expire.clearAll();
        },
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/fund_management.html',
            controller:'FundManagementCtrl'
          }
        }
      })
      .state('dashboard.apply_help',{
        url:'/apply_help',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/apply_help.html',
            controller:'ApplyHelpCtrl'
          }
        }
      })
      .state('dashboard.accept_help',{
        url:'/accept_help',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/accept_help.html',
            controller:'AcceptHelpCtrl'
          }
        }
      })
      .state('dashboard.apply_help_view',{
        url:'/apply_help_view',
        views:{
          'detail@dashboard':{
            templateUrl:'views/tutorial/apply_help.html'
          }
        }
      })
      .state('dashboard.accept_help_view',{
        url:'/accept_help_view',
        views:{
          'detail@dashboard':{
            templateUrl:'views/tutorial/accept_help.html'
          }
        }
      })
      .state('dashboard.confirm_help_view',{
        url:'/confirm_help_view',
        views:{
          'detail@dashboard':{
            templateUrl:'views/tutorial/confirm_help.html'
          }
        }
      })
      .state('dashboard.bonus_logs',{
        url:'/bonus_logs',
        access_level:role.user,
        resolve:{
          bonusLogs:function(UserService){
            return UserService.getBonusLog(1);
          }
        },
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/bonus_logs.html',
            controller:'BonusLogCtrl'
          }
        }
      })
      .state('dashboard.active_transfer',{
        url:'/active_transfer',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/active_deal.html',
            controller:'TransferCtrl'
          }
        }
      })
      .state('dashboard.match_transfer',{
        url:'/match_transfer',
        access_level:role.user,
        views:{
          'detail@dashboard':{
            templateUrl:'views/dashboard/match_deal.html',
            controller:'TransferCtrl'
          }
        }
      })
});
